# Generated by Django 3.1.1 on 2021-04-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFactInv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agregar_productos',
            old_name='descripcion_producto',
            new_name='nombre_producto',
        ),
    ]
