# Generated by Django 3.1.1 on 2021-04-28 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFactInv', '0002_auto_20210428_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agregar_productos',
            old_name='existencia',
            new_name='cantidad',
        ),
    ]
