# Generated by Django 3.1.1 on 2021-05-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFactInv', '0003_auto_20210428_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_factura',
            old_name='cantidad',
            new_name='cant_facturar',
        ),
        migrations.AddField(
            model_name='detalle_factura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
