# Generated by Django 3.1.1 on 2021-05-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFactInv', '0006_auto_20210507_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encabezado_factura',
            old_name='descuento',
            new_name='descuento_total',
        ),
        migrations.RemoveField(
            model_name='encabezado_factura',
            name='subtotal',
        ),
    ]
