# Generated by Django 3.1.1 on 2021-05-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFactInv', '0007_auto_20210513_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_factura',
            old_name='cant_facturar',
            new_name='cantidad',
        ),
    ]
