# Generated by Django 3.1.1 on 2021-05-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFactInv', '0008_auto_20210513_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='cantidad',
            new_name='existencia',
        ),
    ]
